### ISSUE TITLE
Codebase Initialization

### ISSUE THREAD

**Issue by DJSR59** [DJSR59/osu-tourney-helper#12]
# Codebase Initialization

## Associated Stories

- [ ] #7 
- [ ] #8
- [ ] #9 
- [ ] #10 
- [ ] #11 

## Definition of Done

- [ ] Epic is defined
- [ ] Stories are broken down and defined
- [ ] Stories are completed and merged into `dev`
- [ ] Stories are tested
